<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>

    <PackageId>GeneticAlgorithms</PackageId>
    <Authors>Stefan Alfbo</Authors>
    <Description>A small F# library for experimenting with genetic algorithms, providing a compact, generic execution pipeline for evolving chromosomes. Usable from both F# and C#.</Description>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageProjectUrl>https://github.com/stefanalfbo/GeneticAlgorithms</PackageProjectUrl>
    <RepositoryUrl>https://github.com/stefanalfbo/GeneticAlgorithms</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageTags>genetic-algorithm;evolutionary-algorithm;optimization</PackageTags>
    <PackageIcon>icon.png</PackageIcon>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="Chromosome.fs" />
    <Compile Include="GenerationInfo.fs" />
    <Compile Include="Problem.fs" />
    <Compile Include="Distance.fs" />
    <Compile Include="Crossover.fs" />
    <Compile Include="Mutation.fs" />
    <Compile Include="Reinsertion.fs" />
    <Compile Include="Probes.fs" />
    <Compile Include="Options.fs" />
    <Compile Include="Selection.fs" />
    <Compile Include="Genetic.fs" />
    <Compile Include="Interop.fs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="/" />
    <None Include="../../assets/icon.png" Pack="true" PackagePath="/" />
  </ItemGroup>

</Project>
